### ISSUE TITLE
Problem: Ecko not available for installation on Yunohost

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#253]
https://github.com/YunoHost/apps#how-to-add-your-app-to-the-application-catalog

**Comment by weex** [comment]
For tracking: https://github.com/YunoHost/apps/pull/1265

**Comment by weex** [comment]
Listed now but with a "broken" tag which is just part of the process for new apps on YunoHost. Should clear tomorrow and we can announce.

**Comment by MakaryGo** [comment]
I think it can be closed as per https://github.com/YunoHost/apps/commit/d1fde4d4e5421537709aea20aff8e24153d71b97

**Comment by weex** [comment]
Agreed
