### ISSUE TITLE
Problem: Need a new logo and favicon to replace vanilla Mastodon one

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#254]

**Comment by MakaryGo** [comment]
As per  https://github.com/mastodon/mastodon/pull/4306, files that need changing of logo:
app/javascript/images/background-photo.jpg
app/javascript/images/boost_sprite.png
app/javascript/images/fluffy-elephant-friend.png
app/javascript/images/logo.png
app/javascript/images/logo.svg
app/javascript/images/logo_alt.svg
app/javascript/images/logo_full.svg
app/javascript/images/mastodon.jpg
app/javascript/styles/about.scss
app/javascript/styles/containers.scss
app/views/about/show.html.haml
app/views/layouts/admin.html.haml
app/views/layouts/auth.html.haml
public/android-chrome-192x192.png
public/apple-touch-icon.png
public/badge.png
public/browserconfig.xml
public/favicon-dev.ico
public/favicon.ico
public/mask-icon.svg
public/mstile-150x150.png

**Comment by PaulaToThePeople** [comment]
I found this "magic stones" graphic, licensed under GNU GPL 2+.

![grafik](https://user-images.githubusercontent.com/84655636/144220256-a5bf41c0-a24b-4e46-91fb-11ff51eb8f38.png)
Source: https://commons.wikimedia.org/wiki/File:Tux_Paint_magic_stones.svg

**Comment by MakaryGo** [comment]
I'm actually working on a brand new one :) Here's the first sketch:
![image](https://user-images.githubusercontent.com/24472656/144222983-8b3cb580-929f-447a-9a00-3e34eeadfc37.png)
It was inspired by conversation with @weex on our Matrix channel regarding the fact that Fediverse is an ecologic project itself :)

**Comment by weex** [comment]
Closing since we added the new logo. From here it's a matter propagating it to all of the other places in the software.
