### ISSUE TITLE
Problem: It's not possible to follow or subscribe to a #hashtag

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#258]
This would be nice so that people can keep up with certain topics without having to enter advanced mode or manually search out the hashtags whenever they think of it. 

Possible solution:
* Fedibird seems to have implemented a reasonable way to do this. https://github.com/mastodon/mastodon/issues/1096#issuecomment-658299970

**Comment by weex** [comment]
Another potential solution based on DHT with estimates of scaling to Twitter-levels:
https://git.orlives.de/schmittlauch/paper_hashtag_federation/src/branch/master/paper_hashtag_federation.pdf

**Comment by Mansh05** [comment]
@weex This is an interesting feature, We could actually build a easy plugin for this one.

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
