### ISSUE TITLE
Problem: Mastodon in email templates 

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#259]
Email template says "Mastodon hosted on example.com" in footer when it should say Ecko.

**Comment by Mansh05** [comment]
Fixed the issue by renaming "Ecko" currently, If you have anything else in mind, Please let me know will change accordingly.

**Comment by weex** [comment]
It's probably that simple, make a PR and we'll merge it.

**Comment by Mansh05** [comment]
Fixed this, closing it.
