### ISSUE TITLE
Problem: Error trying to import simplified blocklist

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#261]
Created a blocklist with the following contents and attempted as an admin to upload from Preferences -> Moderation -> Federation.
```
example.com
example.org
```

But get the following error on import. It works if the blocklist is of the form output by the export function, but such blocklists are not readily available, so the simple format of one domain per line could be accepted, perhaps with a warning that the domain blocks will merge with the existing ones.
```
web_1        | [guid] [paperclip] Trying to link /tmp/RackMultipart20211107-12-vpiaot.txt to /tmp/94245a752f2353b9820ca1663626a820211107-12-18znzsq.txt
web_1        | [guid] [paperclip] Trying to link /tmp/94245a752f2353b9820ca1663626a820211107-12-18znzsq.txt to /tmp/94245a752f2353b9820ca1663626a820211107-12-13uyzh2.txt
web_1        | [guid] Command :: file -b --mime '/tmp/94245a752f2353b9820ca1663626a820211107-12-13uyzh2.txt'
web_1        | [guid] [paperclip] Trying to link /tmp/94245a752f2353b9820ca1663626a820211107-12-18znzsq.txt to /tmp/94245a752f2353b9820ca1663626a820211107-12-65l0x5.txt
web_1        | [guid] [paperclip] Trying to link /tmp/94245a752f2353b9820ca1663626a820211107-12-18znzsq.txt to /tmp/94245a752f2353b9820ca1663626a820211107-12-gvkeem.txt
web_1        | [guid] method=POST path=/admin/export_domain_blocks/import format=html controller=Admin::ExportDomainBlocksController action=import status=500 error='NoMethodError: undefined method `strip' for nil:NilClass' duration=73.54 view=0.00 db=6.03
web_1        | [guid]   
web_1        | [guid] NoMethodError (undefined method `strip' for nil:NilClass):
web_1        | [guid]   
web_1        | [guid] app/controllers/admin/export_domain_blocks_controller.rb:33:in `block in import'
web_1        | [guid] app/controllers/admin/export_domain_blocks_controller.rb:28:in `each'
web_1        | [guid] app/controllers/admin/export_domain_blocks_controller.rb:28:in `import'
web_1        | [guid] app/controllers/concerns/localized.rb:16:in `block in set_locale'
web_1        | [guid] app/controllers/concerns/localized.rb:15:in `set_locale'
```

Related to #260

**Comment by weex** [comment]
Here's an example blocklist from the export.
[domain_blocks.csv](https://github.com/magicstone-dev/ecko/files/7493355/domain_blocks.csv)

**Comment by Mansh05** [comment]
@weex, I have done this and now you can upload csv files with only domains as the input.
There are few things that i took into consideration while doing so.

There are few fields which i made it default as its required.
1. severity: suspend
2. reject_media: false
3. reject_reports: false
4. public_comment: nil
5. obfuscate: false.

And the hint message also edited to 
CSV file exported from another Ecko or Mastodon server, Please make sure that any existing domains will be merged with the new configuration. You can also add csv with only domains which will take in default values

Please find the attached UI for it as well
![Screen Shot 2021-11-17 at 8 34 59 PM](https://user-images.githubusercontent.com/29198261/142220564-553d5d66-07b0-4e47-b6ff-d2abdc50d61d.png)

I actually coded and tried to push, I guess i need access to the repo to push.

Let me know if i need to do anything more than this?

**Comment by weex** [comment]
I'll make some minor wording changes after, but make a PR and if CI passes I'll merge it.

**Comment by Mansh05** [comment]
@weex Sure, I will make a pr and check the CI results as well. Thanks
