### ISSUE TITLE
Problem: Import of blocklist not available in API

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#262]
Today I setup Mastodon.py in an attempt to import a domain blocklist in CSV format (related to #260).but was not able to find an endpoint for the feature.

Possible solution: Without resorting to cookie-based hacks, the API could expose an endpoint to enable import of a blocklist CSV.

**Comment by Tak** [comment]
There are no api endpoints at all to do with blocks/allows, or really any part of administration except for reporting.

I think the [command-line admin interface](https://docs.joinmastodon.org/admin/tootctl/) is probably the best place to slot something like this into the existing landscape.
