### ISSUE TITLE
Problem: There's no demo server running

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#265]
This means people who want to test out Ecko fully have to install it. Throwaway accounts work for non-admin but admin really does require install or demo. If #253 is solved, then this is slightly less of a concern.

**Comment by weex** [comment]
Potential solution: Create a demo mode that disables registration, has admin and user demo accounts, doesn't send emails, and clears all data on a daily basis.

**Comment by Mansh05** [comment]
@weex, Few question on this issue.
1. Where are we hosting the staging server.
2. Domain for the app

I can prepare the web server, nginx and letsencrypt for https but might need to configure few things to disable the things you mentioned above.

Let me know of it, I will go forward with it then.

**Comment by weex** [comment]
I had planned to install it on ecko-demo.magicstone.dev as an app based on YunoHost. So basically would do a standard install through YunoHost, which is a non-docker installation, then make the necessary changes. Here's the install script that YunoHost uses: https://github.com/YunoHost-Apps/ecko_ynh/blob/master/scripts/install

It would be best if there were a patch we could apply (or if it's just configuration a step-by-step howto) to make the demo server. Ideally others could setup demo servers more easily from such a patch or doc as well. Either way it can take the form of a PR on this repo.

**Comment by Mansh05** [comment]
@weex i will write a demo-setup readme here so that the devop deploying this will have some context on it.

**Comment by Mansh05** [comment]
The Pr for this has been merged. Its fixed now, closing it

**Comment by weex** [comment]
That PR was #280
