### ISSUE TITLE
Problem: Viewing replies to a boosted post doesn't show all replies

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#266]
For example after [this post](https://cybre.space/@SuricrasiaOnline/107268601617381136) was boosted, I clicked on replies and saw the following. If I visit the link to the post however, I see nine other replies including one from the author of the post.

<img width="377" alt="Screen Shot 2021-11-13 at 12 25 59 AM" src="https://user-images.githubusercontent.com/38776/141611800-90e1f264-91aa-45c1-806f-ca2b66cadd0b.png">

**Comment by Mansh05** [comment]
@weex, I will investigate this and see what could be happening here

**Comment by Mansh05** [comment]
@weex, reproduced the issue and looking into this one. Once fixed, i will raise a pr.

**Comment by Mansh05** [comment]
First the cache is one problem, and the other problem is after 15 replies, It doesnt show anymore. Will figure out this too

**Comment by weex** [comment]
Yes, the way messages are propagated by Mastodon and others makes this tricky, but if we implement some limited and focused crawling, perhaps at the user's command, then the picture can become much clearer.

**Comment by Mansh05** [comment]
@weex, The whole status context which these replies are fetched is a spider web. Associations never ending and the request made is quite a heavy one. I m still looking at it by traversing through each command. I will map it out and write my findings here in a diagrammatic format

**Comment by Mansh05** [comment]
@weex, just went through the process again and finally found the flow working. Actually the thread of status works.
I tested locally for almost 5 to 6 different toots and works perfectly fine. The problem with 15 replies was that the sidekiq was on scheduled job and was blocking the process, When i run few process, it works perfectly fine.

Can we test this in our test server. If you could give me the test domain then i will try and reproduce it there and see. Thanks

**Comment by weex** [comment]
We don't have a test server currently but perhaps you could clarify what's needed.

**Comment by Mansh05** [comment]
Actually if we had a test server to work on. We could reproduce this issue and debug it well. For me, the post that you had looked in might have had an infra failure in the background. I faced it similarly when my sidekiq was over performing tasks and failed to load all the replies correctly even though toot got added to my feeds. A test server would actually help us rerun the process as well but it all depends on the highest of priorities.

**Comment by weex** [comment]
Ok, that makes sense. I'll create a debian droplet which you can setup for this purpose, just PM me on matrix with an ssh pubkey when you're ready.

**Comment by weex** [comment]
@Mansh05 Created a droplet at test-ecko.magicstone.dev and added your ssh key from github to root.

**Comment by Mansh05** [comment]
Thanks, Got in, will start setting up now. I will setup the following 
1. Puma server for the app
2. Postgres and Redis, redis i will probably make it work through docker
3. Ngnix setup
4. certbot setup for lets encrypt
5.  Sidekiq service setup

Just few questions here are.
1. What domain would we put the reverse proxy on? If you could please look into this, If you want me to purchase it I can do it as well. The only setup at dns would be to add A record or a CNAME record.
2. Do you want the emails to trigger for testing or do we follow the setup docs like [here](https://github.com/magicstone-dev/ecko/blob/main/DEMO_SERVER_SETUP.md)
 If you want the email setup to work then there are two options we can go with.
1. Postfix (relay server setup)
2. SES aws setup, much easier to do it.

**Comment by weex** [comment]
test-ecko.magicstone.dev is good for the reverse proxy.

If all emails can go to a local mailbox that would be great. Since it's just for testing, I wouldn't expect anyone be able to sign-up most of the time or for any of important info to be in the mailbox. Just let me know how to access it via CLI or url.

**Comment by Mansh05** [comment]
@weex, Test server created,
https://test-ecko.magicstone.dev
Please dont test it today, need to fix some mailer issue then it should be good to go, I will inform here.

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
