### ISSUE TITLE
Problem: Version number displayed by ui is misleading

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#267]
Currently v.3.4.9001 as a meme because C4 process also doesn't require releases. It would be better if something release-independent like a commit hash or capture date were put there instead. Biased toward a date since it can be ordered if in a format like yyyymmdd.

**Comment by Mansh05** [comment]
@weex what is the capture date, is it the last deployed date. I will change this and create a pr.

**Comment by weex** [comment]
It would be best if it were the date of last commit or something that were generated automatically when we merge into main.

**Comment by Mansh05** [comment]
@weex, Maybe we might need to tackle this during CI/CD pipeline. Getting the data directly in the code might be a tricky approach to follow. Normal git deployment in a server would allow Rails to access data from the system but a docker deployment might not get the git data when it goes to production. 

The another approach is to capture the time when the server starts, we could easily get that data and use it to bind it.

**Comment by weex** [comment]
I feel like a git hook might be best. Just drop the date like yyyymmdd into a file and have the ui and nodeinfo render that. One of the uses for this date-based version is so YunoHost can pull upgrades automatically when we're ready for that.

**Comment by MakaryGo** [comment]
There is quite a lot of software that uses _rolling release_ model, but I personally have used only Arch Linux I believe.
They number their releases in format of `YYYY.MM.DD`, which seems convinient to me as well, and additionally they add version of Linux kernel shipped with release.
Only thing that concerns mewith this model, is the necessity of CI setup - so that Ecko v. 2021.11.25 would mean _a working build from that day_...

**Comment by weex** [comment]
> the necessity of CI setup - so that Ecko v. 2021.11.25 would mean _a working build from that day_...

In that respect we're covered in so far as passing CI is a requirement for PR merge and so `main` should always be in passing state.

**Comment by MakaryGo** [comment]
Would format `%F` and `%F.%s` work for you?
E.g. for a build finished right now it vould be
`v.2022-02-23` and `build 2022-02-23.1645657048`

**Comment by weex** [comment]
Whatever you decide if you're implementing is fine to try. As an observation, we only need the last 6 digits of the timestamp.

**Comment by MakaryGo** [comment]
Yeah, but I was thinking that using standard ISO-8859 format wouldn't hurt, and could maybe have some uses

**Comment by weex** [comment]
It could, I'm just aware that version numbers are displayed places like fediverse.observer and a very long one might make a special case of Ecko.

**Comment by MakaryGo** [comment]
That's valid, I didn't think of that.

**Comment by MakaryGo** [comment]
Apparently Glitch doesn't care about it, they append `-glitch` to their app version

**Comment by weex** [comment]
I don't think there's a limit in the nodeinfo spec. We're solving a valid issue of rolling release so in our theory any fix gets merged.

FWIW
v2022-02-25.1645842315 is 22 chars
v3.4.6+glitch is 13

**Comment by weex** [comment]
I thought that was the unix timestamp

**Comment by MakaryGo** [comment]
Oh, yeah, but there is no sense in using the same data (date) in two different formats tho.

**Comment by MakaryGo** [comment]
So, it turns out that we don't have to reinvent the wheel, there is a protocol with lots of case studies:
https://calver.org/

**Comment by MakaryGo** [comment]
There's also a https://github.com/fregante/daily-version-action

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
