### ISSUE TITLE
Problem: There's no Teams, i.e. way for an org or group of people to post from an account

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#276]
From an old issue in Mastodon:

"One of the most used features of Twitter for me is [Twitter teams](https://help.twitter.com/en/using-twitter/tweetdeck-teams), which let's a group of people run a single account, without sharing password."

"We are the team behind ubuntu-ir which now post update statuses in twitter and wanna migrate to mastodon. We have a shared account there between all of the team members and every member can post as this account."

"There are some channels (for announcing, and they're not groups) on Telegram that I co-run with friends and it's pretty handy there too. I'd be in favour of this feature."

**Comment by Mansh05** [comment]
We could have a UI here to select accounts that i can access based. For example 
1. Since we already have an account model, we could extend it by letting it have many users associated with it as a team. 
2. This way, a donot have to login to a different account to maintain it, rather he/she can easily perform certain actions to the account here.

What do you think @weex?

**Comment by weex** [comment]
@Mansh05 Sounds good but if you want to discuss the exact usage that may be helpful. Main wonder how you see the flow working for creating a team and permissions around maintaining it after that. I suppose any change of ownership could be assisted by an admin if say something happens to the account that created the team.

**Comment by Mansh05** [comment]
@weex Sure we could discuss the exact usage then would be great, I will follow that workflow and come up with something on that as a plugin. Let me know when can we discuss about it or if you want to document it here the expectation as well then it would be fine as well.

**Comment by weex** [comment]
Ok, here's the proposed UX:

A team account will be a regular account just like any other. If someone wants to create one, they'll do it through the normal registration process.

Then we add to all accounts the ability to authorize Admins and Contributors.
* Contributors can post/boost/delete posts/follow and unfollow.
* Admins can add/remove other Contributors or Admins.

If administration gets abused by an Admin going rogue. The original account creator should have the password to login to the team account directly and fix it.

**Comment by Mansh05** [comment]
@weex , understood, will work on it and come up with a pr here. Thanks.

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
