### ISSUE TITLE
Problem: There's no documented process to migrate from Mastodon

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#288]

**Comment by MakaryGo** [comment]
I actually just finished a succesful migration from `glitchsoc v3.4.3+glitch` to `ecko v 3.4.9001` without any big problems, so I suppose I could start working out a documentation?

**Comment by weex** [comment]
That's great news. Our version number is a bit of a meme until we solve #267 so you might include the date or commit of Ecko that you migrated to, but any doc will be a great start.

**Comment by MakaryGo** [comment]
Do you think a page on the wiki would be enough?

**Comment by weex** [comment]
Absolutely. Edit boldly as they say.

**Comment by PaulaToThePeople** [comment]
I have 3 Mastodon instances.
One is standard Mastodon hosted by MastoHost.
One is standard Mastodon hosted via YunoHost.
And one is a slight Mastodon fork (5000 character limit) hosted by a friend.
Do you two think it will be possible to migrate them all to Ecko hosted via YunoHost?

**Comment by weex** [comment]
Exciting! The main concern would be database migration and by that I mean not moving the data but once it's loaded into a new db that it upgrades cleanly to the current schema. Another concern would be media breakage so that's something I would check in testing. There are tootctl commands for media maintenance that may help.

Probably obvious but I'd definitely want to reduce the risk by testing, for example trying the migration under a test domain to see that db migration works with no errors or new warnings, then set it up under a real domain. As long as you don't make any posts/boosts or follow anyone, the rest of the network shouldn't know about your test instance(s).

Finally, when you feel ready set a maintenance window and do an install for real, loading and migrating the db, switching DNS, getting the SSL certs in YunoHost and there you go. I'd advise switching one at a time from smaller to bigger (less user impact if anything goes wrong) and newer to older (fewer changes to be made).

If you decide to go forward with this, please make issues for any snags you run into no matter how small. If done in a non-time-critical and risk-minimizing way I think this can be a great experience for us all!

**Comment by MakaryGo** [comment]
@PaulaToThePeople most definitely! The instance I did migrate today was also powered by Yunohost, it didn't cause any problem, on the contrary, it gave me an opportunity to experiment a little thanks to the yunohost app backup.
I'll do my best to make the tutorial ready tomorrow.

**Comment by MakaryGo** [comment]
So it's officially WIP 😊
https://github.com/magicstone-dev/ecko/wiki/Migrating-from-other-Mastodon-flavours

**Comment by MakaryGo** [comment]
Guide finished, but before closing the issue I'd like someone to test it.

**Comment by MakaryGo** [comment]
Guide finished, but before closing the issue I'd like someone to test it.

**Comment by PaulaToThePeople** [comment]
`RAILS_ENV=production ./bin/tootctl media remove` gives me a "no such file or directory" error.
I'm in /var/www/glitchsoc

**Comment by MakaryGo** [comment]
As per the guide:
> To get them, first you have to go to your app location (cd /var/www/mastodon/live/ on YunoHost). If you use Glitch, replace mastodon with glitchsoc.

**Comment by PaulaToThePeople** [comment]
Same result.

**Comment by MakaryGo** [comment]
You are in the `/var/www/glitchsoc/live` ?

**Comment by weex** [comment]
Tried the same and got this error:
```
/var/www/ecko/live# RAILS_ENV=production ./bin/tootctl
/usr/bin/env: ‘ruby’: No such file or directory
```

**Comment by MakaryGo** [comment]
As user root?

**Comment by PaulaToThePeople** [comment]
yes

**Comment by MakaryGo** [comment]
Okay, so I probably have a local $PATH set, let me think about how to hack it...

**Comment by MakaryGo** [comment]
Okay, so I probably have a local $PATH set, let me think about how to hack it...
