### ISSUE TITLE
Problem: Ecko doc page on Yunohost isn't formatted very well

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#292]
https://yunohost.org/en/app_ecko needs some newlines and for the links to be linked.

**Comment by weex** [comment]
https://github.com/YunoHost/doc is the repo where that's set

**Comment by tituspijean** [comment]
Note that it looks like the logo is missing. You may have forgotten a `git add` ;)

**Comment by weex** [comment]
@tituspijean Good catch! Yes, waiting to add out of respect for the artist :)

**Comment by weex** [comment]
Closing, will PR logo once that becomes available.
