### ISSUE TITLE
Problem: Static settings UI not populated by default

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#297]
Static settings are only populated once they are set, not by default after the db:migrate was done to add them.

<img width="538" alt="Screen Shot 2021-12-05 at 6 55 40 PM" src="https://user-images.githubusercontent.com/38776/144779848-82f2e0cc-3108-4229-9d28-f23a97c4826b.png">

**Comment by Mansh05** [comment]
@weex, for this there are two ways to tackle them, Either we introduce default values to the migration files or we can create a task to populate them. I will create  a pr on this.

**Comment by Mansh05** [comment]
@weex i think we can close this. This was fixed in #317
