### ISSUE TITLE
Problem: Label text on profile user fields screen doesn't reflect setting

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#300]
Here where 3 were allowed, the text still says 4.

<img width="423" alt="Screen Shot 2021-12-05 at 7 12 03 PM" src="https://user-images.githubusercontent.com/38776/144781181-a1f03fa2-e554-43c4-8fcb-b62ce659ceba.png">

**Comment by Mansh05** [comment]
Will fix this after #317 is merged.

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
