### ISSUE TITLE
Problem: It's hard to find Ecko instances / It's hard for Ecko instances to be found

### ISSUE THREAD

**Issue by ghost** [magicstone-dev/ecko#309]
It's easy to find a Mastodon instance with the help of joinmastodon.com and it's easy for a Mastodon instance to by found by potential users by adding the instance to joinmastodon.com
But apparently instances that use Mastodon forks like Ecko won't be added to joinmastodon.com

On my Mastodon instances I constantly get new users, but my Ecko instance almost nobody joins.
The only ways to find Ecko instances I know of are the wiki here and https://ecko.fediverse.observer/list

Proposed solution: Create a website for Ecko, like joinmastodon.com for Mastodon.

PS: What would also help is to ask all the websites on the Fediverse to add Ecko to their lists.
E.g. I have added a page on Ecko on the not yet publicly announced Fediverse Wiki: https://joinfediverse.wiki/index.php?title=What_is_Ecko%3F

**Comment by weex** [comment]
Thinking along these lines I registered joinecko.com and .org when the name was chosen. 

I'm wondering how to add value on the fediverse.observer db but a quick fix would be to redirect those to the fediverse observer list or wizard.
