### ISSUE TITLE
Problem: Deepsource erroring with File not found: /code/public/sw.js

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#312]
Since a day ago, deepsource's javascript check has been failing due to this file not found error. Strange thing is /code/public/sw.js doesn't exist in our repo.

Submitted a ticket with deepsource to see if there's something on their end. Error appeared when nothing related was changed.

**Comment by weex** [comment]
Got a response that Deepsource support is looking into this.

**Comment by weex** [comment]
Latest push to #308 passed so this may have been solved.

**Comment by Mansh05** [comment]
@weex i guess we could close this issue since its fixed?

**Comment by weex** [comment]
Yes, got a response it was due to some error in their analyzer with symlinks.
