### ISSUE TITLE
Problem: More than 4 poll options causes overlapping in the composition form

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#314]
When setting poll options to 5 the layout breaks as shown.

<img width="288" alt="Screen Shot 2021-12-09 at 1 13 17 PM" src="https://user-images.githubusercontent.com/38776/145476714-13556529-7cd9-46c2-aad4-e46724c06a09.png">

**Comment by Mansh05** [comment]
![Screen Shot 2022-01-24 at 12 53 33 PM](https://user-images.githubusercontent.com/29198261/150735546-7a986913-6c4e-4af6-beca-0e331a3b8f0b.png)
I think the overflow y gets applied and we need to scroll this one. Maybe we can keep as it is as its not breaking but just overflowing and we have the scroll as well

@weex Do you have any other suggestion here?

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
