### ISSUE TITLE
Problem: Static Settings don't take effect immediately

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#315]
The Static Settings screen at /settings/static_settings now allows the administrator to change max poll options, poll option length and other things but these settings don't take effect immediately.

Proposed solution: Place some informational text on that screen, noting that a restart is required for these settings to take effect.

**Comment by Mansh05** [comment]
Now we dont need any restart here with it being fixed here. #317 The settings will take immediate effect now.
