### ISSUE TITLE
Problem: Blocklist can't be exported automatically to a publicly accessible location

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#316]
Since blocklists can be imported via command line which means they can be scripted and scheduled, the missing piece for automated instance blocking is being able to publish an instance blocklist.

Proposed solution: Create a tootctl command that exports the current blocklist to a stable and publicly-accessible location like https://example.com/system/moderation/blocklist.csv. The command might skip obfuscated domain names (see https://example.com/admin/domain_blocks/new) or fail with a helpful message if advertising the list of domain limitations is disabled.

**Comment by Mansh05** [comment]
Since i have worked with blocked list, i could work here. @weex could you please give some use case or context on this one. I can get started after that.

**Comment by Mansh05** [comment]
@weex i guess we can close this. Should have been fixed with #320
