### ISSUE TITLE
Problem: New Toot doesn't get displayed when creating one.

### ISSUE THREAD

**Issue by Mansh05** [magicstone-dev/ecko#318]
Currently whenever i create a status or toot, it doesn't get displayed in the feed but when I refresh the page, it's displayed. The users might think their toot was not created and re post again. Will be great to have my toot which i create, displayed at first.

**Comment by weex** [comment]
I agree this is a bit strange UX. I suppose there could be some trickiness in solving it but seems like an accurate and valuable problem to me!

**Comment by weex** [comment]
As a counterpoint, I just posted a toot and it did show in the timeline immediately. Maybe this has to do with broken a streaming connection?

**Comment by Mansh05** [comment]
This can be closed as its mostly to do with infrastructure error with streaming. We can mention this issue when we face that.
