### ISSUE TITLE
Problem: Ecko may not have good accessibility 

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#321]
This is a potential issue that is worth further research. 
Resource: https://uxplanet.org/a-primer-to-web-accessibility-for-designers-2c548448c612

**Comment by MakaryGo** [comment]
That's a bit vague, what exactly do you have in mind @weex ?

**Comment by weex** [comment]
Basically testing against the various aspects mentioned in the article. I ran across https://github.com/mastodon/mastodon/issues/11420 a while back and thought it was worth a look should someone be interested in that.

**Comment by rkingett** [comment]
[Dropping this CSS style here to detect non-described media.](https://gist.github.com/FiXato/3de505b04efefd49a1e3568b70545234) Perhaps this could be a native theme for all instances?

**Comment by weex** [comment]
Created https://github.com/magicstone-dev/ecko/issues/387 since we try to keep issues focused on one problem.

**Comment by weex** [comment]
Closing this as we should keep issues more focused. We make better progress when specific issues like undescribed media are brought up.
