### ISSUE TITLE
Problem: Docker-compose installation gives 502

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#329]
Updated c4.social to the latest tag currently which is https://hub.docker.com/repository/registry-1.docker.io/dsterry/ecko/builds/7d6caaaa-ffba-4fd6-bfc7-e361f5633823 and it gave a 502.

Error logs from web service: https://gist.github.com/weex/a38b96e5f38bd8cab62cacecb75922cc

Looks like git became a runtime requirement with ecko-plugins.

Proposed solution:
Don't require git as many times people don't need or want that installed in production.

**Comment by weex** [comment]
To rollback I had to find the previous image I was using with `docker image list` and then put that id like `image: 2197b82e5e84` in the three ecko image locations in docker-compose.yml. Then `docker-compose up -d` and in 30s we were back!

Helpful doc: https://docs.docker.com/compose/compose-file/compose-file-v3/#image

**Comment by Mansh05** [comment]
@weex the git issue doesnt come anymore with docker-compose-up anymore.
