### ISSUE TITLE
Problem: I can't crop photos before posting

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#334]
Sometimes I like to share photos from mobile where I tend to take them, but I don't have any ability to make a simple edit like cropping without using another app or transferring to my computer so what could take a few seconds, takes minutes and this sometimes means I don't post at all or have to remember to do it later.

Proposed solution:
Add the ability to crop an image before posting. Maybe there's an editing UI library that enables other simple edits like rotate/markup that would also help.

**Comment by Mansh05** [comment]
I have worked with this before and seems to work nicely. https://www.npmjs.com/package/cropperjs

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
