### ISSUE TITLE
Problem: Compose form is too busy (a suggestion to make it simpler)

### ISSUE THREAD

**Issue by jorgesat** [magicstone-dev/ecko#340]
The compose form looks rather busy with the extra option of choosing to post as local-only.

*Proposed solution:*
I suggest to make it simpler by moving the local-only option to the privacy drop-down menu as shown in the image below:
![Suggestion](https://user-images.githubusercontent.com/7603402/146931418-45a5f322-babf-4f06-abc7-49d5b4e38d38.png)

**Comment by j12i** [comment]
this reduces your visibility options from 8 to 5

**Comment by weex** [comment]
Fixed by #402.

@j12i True. If you're missing one of the three possibilities, please make an issue.
