### ISSUE TITLE
Problem: Toots not rendering Markdown

### ISSUE THREAD

**Issue by jorgesat** [magicstone-dev/ecko#341]
It would be nice that toots can be edited using Markdown

*Proposed solution:*
I think other forks like glitch-soc have implemented Markdown.

**Comment by weex** [comment]
I've often wanted the most basics of markdown like being able to highlight `commands`, **bold** and *italics* but I'd be wary of large headings. Let's focus this issue on Markdown, created #343 to track LaTeX seperately.

**Comment by weex** [comment]
Glitch-soc uses the Redcarpet gem to do formatting and currently mentions markdown in these files:
```
app/javascript/flavours/glitch/features/compose/components/options.js
app/lib/formatter.rb
app/models/status.rb
app/views/settings/preferences/other/show.html.haml
lib/tasks/auto_annotate_models.rake
spec/lib/formatter_spec.rb
```

**Comment by Mansh05** [comment]
Some docs for reference that i am referring as well https://glitch-soc.github.io/docs/features/rich-text/

**Comment by Mansh05** [comment]
For this problem, i am trying to replicate same as that of glitch so that i dont complicate it. There ux looks good as well. Almost done with it, WIll be testing and pushing a pr for this.
