### ISSUE TITLE
Problem: Checkout page says "Book for $x"

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#349]
I tend to think of this as "Donate" or "Pay". 

From checkout page:
<img width="410" alt="Screen Shot 2021-12-21 at 4 16 31 PM" src="https://user-images.githubusercontent.com/38776/147013957-13c2643f-5709-43e3-a0c8-26c024f719a2.png">

**Comment by Mansh05** [comment]
![Screen Shot 2021-12-22 at 11 04 03 AM](https://user-images.githubusercontent.com/29198261/147038593-5b8c39d6-a455-4946-bf31-7b3f075a9aac.png)
Fixing this this way. The amount comes itself.
