### ISSUE TITLE
Problem: Need sponsor listing/ranking page.

### ISSUE THREAD

**Issue by Mansh05** [magicstone-dev/ecko#352]
We need to show a list where we show which user/account has sponsored how much or show their tier. This way we will be showcasing the contributions that a particular account has done.

**Comment by weex** [comment]
Some donors may want to remain private as far as public acknowledgement goes so I'd try to support that desire in some way.

**Comment by Mansh05** [comment]
Ah makes sense. We can do that, whenever someone donates and are send back to the thank you page we can ask for their consent whether they want to show case their donation or not. By default it will be private. And we can also have a page where i can see all of my donations made till date and its visibility in the donation ranking.(This i will create another issue)

**Comment by weex** [comment]
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."
