### ISSUE TITLE
Problem: Need documentation for plugins gem and publish it to the gem repository.

### ISSUE THREAD

**Issue by Mansh05** [magicstone-dev/ecko#353]
Before publishing our ecko plugins gems, we need to document it throughly and write a blog so that different instances across the fediverse/mastodon community can use it.

**Comment by weex** [comment]
Might be good to break this into two or more problems specific to each plugin/gem to keep these independent.

**Comment by Mansh05** [comment]
True will do that then, Closing this one as it seems quite generic.
