### ISSUE TITLE
Problem: Sponsor badges are a bit strong

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#357]
The badge is pretty big and filled with a solid color that stands out quite strongly. 

Proposed solution:
Mute color slightly and go with outline only.

**Comment by Mansh05** [comment]
How about the badges similar to the one below.
![Screen Shot 2021-12-28 at 4 40 45 PM](https://user-images.githubusercontent.com/29198261/147558035-23bc10ae-d2c4-43cf-a377-c91351e0b8ff.png)

**Comment by weex** [comment]
If it's like emoji sized that would do it for me. Part of the issue is that it seems hard to modify the styling. Maybe a configurable emoji or custom emoji with 🥈🥇🥉used for the default packages.

**Comment by Mansh05** [comment]
Sounds good @weex, I will add db column so that we can mention the color of the badge. We can just have one styling but the color changes based on the value provided in the db.

**Comment by Mansh05** [comment]
Creating a new issue for customizable emoji in the plugin repo. [here](https://github.com/magicstone-dev/ecko-plugins/issues/7)

**Comment by Mansh05** [comment]
@weex can we close this? #369 solves this.

**Comment by weex** [comment]
Just want to confirm it somewhere. c4.social is the easiest place once I can update it.

**Comment by Mansh05** [comment]
@weex I think we should close this since its been handled #369. If you think we should keep it open than please reopen it. I will close it for now.

**Comment by weex** [comment]
Yep, thanks
