### ISSUE TITLE
Problem: Staff can't search users by email domain

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#361]
As an administrator, I'd like to search for users by email domain to suspend a set of bot accounts, but searching by email domain seems not to be possible. Tried *example.com, *@example.com. Elastic search isn't enabled so perhaps this search requires that.

**Comment by MakaryGo** [comment]
Try `%@example.com`

**Comment by weex** [comment]
That works! Thanks @MakaryGo. Hope you're doing well.
