### ISSUE TITLE
Problem: Latest docker build (2678b16) puts sidekiq and web in restart loop

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#370]
Just attempted to deploy the latest code to c4.social but sidekiq service was crashing within seconds and web restarted as it failed health check after 30s.

Commit: https://github.com/magicstone-dev/ecko/commit/2678b166f61fb8f93364cf2e3bc45dd40c6af7cf

Log from web service: https://gist.github.com/weex/3ed0ae1e68fc218fcbbca2fb8e221af9

Log from sidekiq service (last two lines repeat a bunch of times):
```
$ docker-compose logs sidekiq
Attaching to ecko_sidekiq_1
sidekiq_1    | bundler: command not found: sidekiq
sidekiq_1    | Install missing gem executables with `bundle install`
```

**Comment by weex** [comment]
Narrowed this error down to starting at the following build:
`dsterry/ecko@sha256:dc735316342259655f25654a82211002ed1dbb7bae5c23cc6982cef3354feae2`
Image id `cb7328290412 `
Last pushed Dec 26, 2021 at 11:42 pm (hub.docker.com doesn't say time zone)

Based on time the commit that introduced the error was: https://github.com/magicstone-dev/ecko/commit/55e214b454dbd0c60d07301edc835f9e7e11ae93 at Dec 26, 2021 at 11:24 pm PST

Build info for that image:
https://hub.docker.com/repository/registry-1.docker.io/dsterry/ecko/builds/51d0aeef-efeb-41ca-bb70-7f7def7b966d

One of the last few lines in the build log is
```
#21 writing image sha256:cb732829041210478a5531064f9ec4830e218835628be64d56b41bfa825accc0 done
```
which includes `cb7328290412` which matches the image id on my machine, closing the confusing loop of docker build, commit and image ids.

**Comment by weex** [comment]
Still a problem after merging #374. Can't seem to find any recent change in Dockerfile that would stop sidekiq from having been installed.

**Comment by weex** [comment]
Suspect sidekiq isn't available to the Sponsors ecko-plugin in the docker image.

**Comment by Mansh05** [comment]
Normally the addition to gemfile would include the plugin there. Let me have a look at this in my local system.

**Comment by Mansh05** [comment]
@weex , https://github.com/javan/whenever/issues/732#issuecomment-993034021 saw this issue as well. I guess why not bump up the docker ruby version from 2.7.4 to 2.7.5?

**Comment by Mansh05** [comment]
@weex Tried multiple different ways to figure out. Could you please find the last commit tag that was deployed to production. With that we can test which commit or code change caused the problem. THanks

**Comment by weex** [comment]
I actually narrowed it down to an exact build. I guess I would wonder if the previous commit were built if that would still fail. So then it's be a dependency like Ecko-plug-ins? https://github.com/magicstone-dev/ecko/issues/370#issuecomment-1004405117

**Comment by Mansh05** [comment]
Let me remove the dependencies. But the issue comes from the time it tries to run rails itself. If it was the plugins issue then the problem should actually come during run time. Currently, "bundle exec rails s -p 3000" execution itself is failing as it cannot find rails within the ruby directory. My assumption is that it could be something to do with new ubuntu updates that caused this? because if it is a runtime issue, it wouldnt run in the local system as well.

**Comment by weex** [comment]
Yeah, could be an unpinned container we're basing on... I guess we could check by rebuilding one of the previous builds to see if it fails now. I'll try it tomorrow if still unknown.

**Comment by weex** [comment]
Built a docker image locally based on 7e6b668cfc7ffa0e3d2204a4e9b8fd64ea586115 and it's doing the restart thing, so I  think that answers that it's something that changed in our build dependencies.

**Comment by weex** [comment]
#379 Fixed it
