### ISSUE TITLE
Problem: tootctl cache clear doesn't work

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#383]
Ran `docker-compose run --rm web bin/tootctl cache clear` which reported `OK` but there was no change in the size of `public/system/cache` or free space on the system.

**Comment by Mansh05** [comment]
From my perspective, Rails cache clear is memory cache and public/system/cache is a system IO cache. Rails cache normally saves in the ram memory right?

**Comment by weex** [comment]
Clearing rails cache doesn't need a tootctl so I think this one is supposed to clear content stored on disk. This directory was 32gb by now and filling up the disk so it is one that wants to be cleared periodically. I'd add storage if it would be useful but I don't think it's necessary to keep the cached data around long term.

**Comment by weex** [comment]
Actually the command is `tootctl media remove` :)
