### ISSUE TITLE
Problem: Issue with .env.production in the Docker setup instructions

### ISSUE THREAD

**Issue by limdingwen** [magicstone-dev/ecko#436]
*Please state the bug, support or feature request in terms of a problem to be solved.*

In "Getting the Ecko Image", step 5 produces an error saying that .env.production is not found.

*(Optional) Proposed solution:*

I fixed it by running `touch .env.production` inside the `~/ecko` directory to satisfy `docker-compose build`. Not sure if that's a hack, request for comment if instructing the user to run `touch .env.production` between step 4 and step 5 is a good idea.

**Comment by weex** [comment]
Thanks for creating this issue. Did you use the pre-built image or build one yourself by doing [step 3](https://github.com/magicstone-dev/ecko/blob/main/docs/INSTALL_DOCKER_COMPOSE.md#getting-the-ecko-image)?

**Comment by limdingwen** [comment]
Thanks for replying. I commented out the `build: .` lines in step 3.

**Comment by limdingwen** [comment]
Ah, seems like we should be using `docker-compose pull` instead.

**Comment by weex** [comment]
That works for me.
