### ISSUE TITLE
Problem: The words "Content Warning" cannot be customised

### ISSUE THREAD

**Issue by limdingwen** [magicstone-dev/ecko#445]
*Please state the bug, support or feature request in terms of a problem to be solved.*

In some parts of the Fediverse, the Content Warning (ActivityPub summary) field is used for more than just warnings, but notices in general, much like an email subject line. The words Content Warning cause confusion in some people joining those parts of the Fediverse.

*(Optional) Proposed solution:*

Allow customisation of the Content Warning word (a suggestion on the Mastodon issue tracker was "Content Notice"). Not sure if admin-level or user-level.

**Comment by weex** [comment]
Do you have a link to discussion of CN as a replacement for CW? 

I've grown used to seeing Content Warning and CW so for me it's not a problem, plus I don't really use it. Still I can see it being a point of friction for new users as to what it is, the best name for it and how it should be used.

**Comment by limdingwen** [comment]
[Here](https://github.com/mastodon/mastodon/issues/20117) is the relevant issue on the mainline issue tracker.

**Comment by BenAveling** [comment]
Yes, there's a lot of discussion about issues beyond changing Warning to Notice, but broad consensus for a change and Notice is far and away the most popular.

But note, there's some potential confusion if the icon changes to [CN], mainly because it currently sits next to [EN], or whatever language the user is using and for a lot of people CN means China/Chinese.

**Comment by weex** [comment]
> But note, there's some potential confusion if the icon changes to [CN], mainly because it currently sits next to [EN], or whatever language the user is using and for a lot of people CN means China/Chinese.

Not in Ecko :) We forked before Mastodon v4.0 so this is how it looked before this PR.

If we want the language selection box from v4.0 someone will need to create an issue here describing the problem it solves.

<img width="292" alt="Screen Shot 2022-11-17 at 8 56 04 AM" src="https://user-images.githubusercontent.com/38776/202508999-f1a415ff-7f58-4a28-ab06-b0562ff2b819.png">

**Comment by weex** [comment]
@limdingwen While not customizable, the wording was changed to "Content Notice" with #450 so I'm closing this. Feel free to re-open if customization is a must-have.
