### ISSUE TITLE
Problem: Ecko's linking in Github to the mastodon/mastodon repository

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#471]
Github's message in the repo (currently "570 commits ahead, 1789 commits behind") gives that impression that the repository is simultaneously out-of-date and very difficult to reconcile. This is misleading since forking and choosing to manage the project via [C4](https://github.com/magicstone-dev/magicstone.dev/wiki/Addendum-to-C4-protocol).

It also makes it difficult to visualize and work among forks of Ecko.

Proposed solution:
Contact github support to have Ecko unlinked from the mastodon/mastodon on Github

**Comment by politas** [comment]
I'd support this as a problem to address.

**Comment by weex** [comment]
Great, just created a ticket with Github support with the option to bring child forks along.

**Comment by weex** [comment]
It's now unlinked.
