### ISSUE TITLE
Problem: Referrer-Policy Privacy issue on small / single user servers

### ISSUE THREAD

**Issue by politas** [magicstone-dev/ecko#475]
The discussion in https://github.com/mastodon/mastodon/issues/21795 has several explanations of the privacy concerns for small & single-user servers related to having Referrer-Policy set to "origin". 

Small and single-user servers are less likely to be set up by people who are fully aware of this technical issue and may not know how to change from the default to make things safer for their users, especially users with identifiable minority/marginalised group membership.

Solution: Default Referrer-Policy should be set to "noreferrer", with any interface for changing it being well documented to explain the privacy implications.

I also believe Ecko should adopt an official policy of making a default install safe for users, with advice for where to find high quality blocklists and default options intended to maximise privacy rather than catering to the commercial goals of third party website owners.

**Comment by politas** [comment]
Ok, looking at the change mentioned in that thread and the code, it looks like we do have the "noreferrer" set on outgoing links.

**Comment by weex** [comment]
Thanks for following this and for highlighting an important difference from Mastodon.

It's good enough for me that this is in our issue tracker because it'll show up in searches, plus C4 should disallow a change to `noreferrer` where there is no valid problem.
